"""Generate PostgreSQL DDL from discovered MSSQL schema."""

from __future__ import annotations

from typing import Any

from transqlate.dump_format import pg_quote_ident, table_key
from transqlate.types_map import pg_type_for_column


def pg_schema_name(mssql_schema: str, target_schema: str | None) -> str:
    if target_schema:
        return target_schema
    if mssql_schema.lower() == "dbo":
        return "public"
    return mssql_schema


def qualified_pg_table(
    mssql_schema: str, table: str, target_schema: str | None
) -> str:
    pg_schema = pg_schema_name(mssql_schema, target_schema)
    return f"{pg_quote_ident(pg_schema)}.{pg_quote_ident(table)}"


def column_def(col: dict[str, Any]) -> str:
    name = pg_quote_ident(col["name"])
    pg_type = pg_type_for_column(col)
    parts = [name, pg_type]
    if col.get("is_identity"):
        parts.append("GENERATED BY DEFAULT AS IDENTITY")
    elif not col.get("nullable", True):
        parts.append("NOT NULL")
    return " ".join(parts)


def create_table_sql(
    table: dict[str, Any], target_schema: str | None, *, drop_if_exists: bool
) -> list[str]:
    mssql_schema = table["schema"]
    name = table["name"]
    qualified = qualified_pg_table(mssql_schema, name, target_schema)
    pg_schema = pg_schema_name(mssql_schema, target_schema)

    stmts: list[str] = []
    if drop_if_exists:
        stmts.append(f"DROP TABLE IF EXISTS {qualified} CASCADE;")

    if pg_schema != "public" or mssql_schema.lower() != "dbo":
        stmts.append(f"CREATE SCHEMA IF NOT EXISTS {pg_quote_ident(pg_schema)};")

    col_defs = [column_def(c) for c in table["columns"]]
    pk = table.get("primary_key") or []
    if pk:
        pk_cols = ", ".join(pg_quote_ident(c) for c in pk)
        col_defs.append(f"PRIMARY KEY ({pk_cols})")

    body = ",\n    ".join(col_defs)
    stmts.append(f"CREATE TABLE {qualified} (\n    {body}\n);")
    return stmts


def foreign_key_sql(
    table: dict[str, Any], target_schema: str | None, *, drop_if_exists: bool
) -> list[str]:
    stmts: list[str] = []
    qualified = qualified_pg_table(table["schema"], table["name"], target_schema)
    for fk in table.get("foreign_keys", []):
        name = fk["name"]
        if drop_if_exists:
            stmts.append(
                f"ALTER TABLE {qualified} DROP CONSTRAINT IF EXISTS {pg_quote_ident(name)};"
            )
        local_cols = ", ".join(pg_quote_ident(c) for c in fk["columns"])
        ref_qualified = qualified_pg_table(
            fk["referenced_schema"], fk["referenced_table"], target_schema
        )
        ref_cols = ", ".join(pg_quote_ident(c) for c in fk["referenced_columns"])
        stmts.append(
            f"ALTER TABLE {qualified} ADD CONSTRAINT {pg_quote_ident(name)} "
            f"FOREIGN KEY ({local_cols}) REFERENCES {ref_qualified} ({ref_cols});"
        )
    return stmts


def index_sql(table: dict[str, Any], target_schema: str | None) -> list[str]:
    stmts: list[str] = []
    qualified = qualified_pg_table(table["schema"], table["name"], target_schema)
    for idx in table.get("indexes", []):
        if not idx.get("columns"):
            continue
        unique = "UNIQUE " if idx.get("unique") else ""
        cols = ", ".join(pg_quote_ident(c) for c in idx["columns"])
        included = idx.get("included_columns") or []
        # PostgreSQL supports INCLUDE for covering indexes
        include_clause = ""
        if included:
            inc = ", ".join(pg_quote_ident(c) for c in included)
            include_clause = f" INCLUDE ({inc})"
        idx_name = pg_quote_ident(idx["name"])
        stmts.append(
            f"CREATE {unique}INDEX IF NOT EXISTS {idx_name} "
            f"ON {qualified} ({cols}){include_clause};"
        )
    return stmts


def apply_schema(
    conn: Any,
    schema_doc: dict[str, Any],
    *,
    target_schema: str | None,
    drop_existing: bool,
    skip_indexes: bool,
    skip_foreign_keys: bool,
) -> None:
    tables = schema_doc.get("tables", [])
    with conn.cursor() as cur:
        for table in tables:
            for sql in create_table_sql(
                table, target_schema, drop_if_exists=drop_existing
            ):
                cur.execute(sql)

        if not skip_foreign_keys:
            for table in tables:
                for sql in foreign_key_sql(
                    table, target_schema, drop_if_exists=drop_existing
                ):
                    cur.execute(sql)

        if not skip_indexes:
            for table in tables:
                for sql in index_sql(table, target_schema):
                    cur.execute(sql)
    conn.commit()


def reset_identity_sequences(
    conn: Any, schema_doc: dict[str, Any], target_schema: str | None
) -> None:
    with conn.cursor() as cur:
        for table in schema_doc.get("tables", []):
            identity_cols = [
                c["name"] for c in table["columns"] if c.get("is_identity")
            ]
            if not identity_cols:
                continue
            qualified = qualified_pg_table(
                table["schema"], table["name"], target_schema
            )
            for col in identity_cols:
                qcol = pg_quote_ident(col)
                cur.execute(
                    f"""
                    SELECT setval(
                        pg_get_serial_sequence(%s, %s),
                        COALESCE((SELECT MAX({qcol}) FROM {qualified}), 1),
                        EXISTS (SELECT 1 FROM {qualified})
                    )
                    """,
                    (qualified, col),
                )
    conn.commit()


def truncate_all(
    conn: Any,
    import_order: list[str],
    schema_doc: dict[str, Any],
    target_schema: str | None,
) -> None:
    tables_by_key = {
        table_key(t["schema"], t["name"]): t for t in schema_doc.get("tables", [])
    }
    qualified = [
        qualified_pg_table(
            tables_by_key[k]["schema"], tables_by_key[k]["name"], target_schema
        )
        for k in reversed(import_order)
        if k in tables_by_key
    ]
    if not qualified:
        return
    sql = "TRUNCATE TABLE " + ", ".join(qualified) + " RESTART IDENTITY CASCADE;"
    with conn.cursor() as cur:
        cur.execute(sql)
    conn.commit()
